language: node_js
node_js:
  - node
services:
  - mongodb
script:
  - npm run test:coverage
  - npm run test:coverage:upload
env:
  global:
    - secure: Y9DgIBVqCLRRxCSSpYnvQB9ROw+zaE1+MiSCb0we8T20uvIhEkF4Uyt53pEnJwDDQhW9yg09JouP0FhMzttHhwu2qEN50nx3JkVDeLGeCc3kdzls8sma+wKzkddiZiHsJa7GtBfC+y+I7ZBG/t92oYIP06nYlohUxCerP2j0q87Fg21r61TQu4yL+BVZu54QVIqx9ED9guQfGjt8pxpoH/t9b7nDt8/GAt4QuWMGirrHjAhpKdxZHeioKKf4996fQaSbRgMZFPLQfKMsnBAEyOy13Mrr7Ni7Enex+e4VwWFvQIB5ixiO/rxoakZzK4tUSVNKToYnoq9tm91IxDBP4waKzItqRWbWnyecueRL6vSOppr4kDlEU8gKjMeNvPyTJrw8sA7Lmx88n6WTrQd1INSnR0CUH9mq/NBK/P+VUOFPJkbeSVhNj5k5eOjKxKx34oCc/IHKARyYXy28JfwWkKooeUoHdy9n8d22428aj5nMMiV7yRnEBcefMoNQEh84LOL+LSYzAOCl3mDi7HTgCuJ3nCl8vLIa/3qE3mQBel7YQCMxQWav5F1jqDuHe2e11ccRZFiI5Qk1rW4F6I+HS78eeud8nUPiXy1dvlM96tmFyN1ATqBlEKY+GZVapbCOv9TS3gBcBfYXOzFoMsgMcNzxgnbBjC9ey1oNfd7uJow=
    - secure: XOQtCVQAAMjXGhN5Wk8OFDSSRBCwJ2EbJdUO/Wdbgjsa6aUN+zSdkXOl9ak2jX0YKrJECQz23uIx2GdhJotC0Yf3xgP7OFkWaGWFTcJfs2WZMS2xUIgA2clx1iJfFZ8ZmGxqfeGp92ctQVLwx3lbZ9Na5B1jC7CaECh8iI9aNet2TG6bTlzNFv6zwzWKVLC1DO2ZJhkkPsN4EgEcFXKi9hNvwfkRk7kUiwm/R5D/SIxS/Nt98hLm2IPuoiAFFwF4TRA/QrkyZbUNorxiUM8Fp2YLL8IQSRpbjn7PKO93KSpryMNAgrsN39S63LfjkJhStBe1WRxy2Fni0JOMe4MRlkIMwVC7aJSanDYVsemkBxbovABIEQxqnC+22j9tQfV4itk/fB1X9cmTv5H6xICPoJkpZoF8hQwKPJs65TO3M9QzcSuKXmYqOczBOgnh8YyhUCiKcjlYkF13+/ruT0aDMiqPMGjHhrsvriGLGPVJ2tzBaymdNzlqqashA5svjmTLkusxj7vUY7iKu8B6QRMpR7M1KElekEcNhNNI7tgPXRLPjvgDgCkY03DJGJ+xyCjkUVoQ+8QSs1wi2Sy1gkrPDhQ8H6vM8CDQjoPt0jzsClcoII3geD5m5RBemZ4OqOd6xH/tsXF6ILU9kee3RtjwH858MHHe+XqCHRLBZgk/zMI=
addons:
  sauce_connect: true
